# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '05_transaction_trans_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
